--[[
test_error.lua - Test error handling
]]

function process()
    error("Error test")
end